## 1. What is the Average Height of US Presidents?

Aggregates available in NumPy can be extremely useful for summarizing a set of values.
As a simple example, let's consider the heights of all US presidents.

This data is available in the file *president_heights.csv*, which is a simple comma-separated list of labels and values.

Find the mean height, the standard deviation of height, and the president who is the smallest and tallest.

You can use `pandas` to read in the file if you want, then cast the column to a `np.array`

In [17]:
import pandas as pd
import numpy as np

df = pd.read_csv('C:/Users/farha/Documents/m1-6-numpy/data/president_heights.csv')

array = df['height(cm)'].to_numpy()

print(str(array.mean()) + " is the mean height of US presidents")
print(str(np.std(array)) + " is the standard deviation of the heights of US presidents")

df2 = df.drop('order', 1)
array2 = df2.to_numpy()
array3 = array2[array2[: , 1].argsort()]
print("At " + str(array3[0][1]) + " cm tall, " + str(array3[0][0]) + " was the shortest president")
print("At " + str(array3[-1][-1]) + " cm tall, " + str(array3[-1][0]) + 
      " and " + str(array3[-2][0]) + " were the tallest presidents")
array3

179.73809523809524 is the mean height of US presidents
6.931843442745892 is the standard deviation of the heights of US presidents
At 163 cm tall, James Madison was the shortest president
At 193 cm tall, Lyndon B. Johnson and Abraham Lincoln were the tallest presidents


array([['James Madison', 163],
       ['Martin Van Buren', 168],
       ['Benjamin Harrison', 168],
       ['John Adams', 170],
       ['William McKinley', 170],
       ['John Quincy Adams', 171],
       ['William Henry Harrison', 173],
       ['James K. Polk', 173],
       ['Zachary Taylor', 173],
       ['Ulysses S. Grant', 173],
       ['Rutherford B. Hayes', 174],
       ['Millard Fillmore', 175],
       ['Harry S. Truman', 175],
       ['Jimmy Carter', 177],
       ['Andrew Johnson', 178],
       ['Franklin Pierce', 178],
       ['Theodore Roosevelt', 178],
       ['Calvin Coolidge', 178],
       ['Dwight D. Eisenhower', 179],
       ['Woodrow Wilson', 180],
       ['George W. Bush', 182],
       ['Herbert Hoover', 182],
       ['Richard Nixon', 182],
       ['William Howard Taft', 182],
       ['Warren G. Harding', 183],
       ['Chester A. Arthur', 183],
       ['Gerald Ford', 183],
       ['James Buchanan', 183],
       ['John Tyler', 183],
       ['James Monroe', 183],
       

# Exercise 2

Recall the polynomial formula

$$
p(x) = a_0 + a_1 x + a_2 x^2 + \cdots a_N x^N = \sum_{n=0}^N a_n x^n \tag{1}
$$

In the **math functions workshop**, you wrote a simple function `p(x, coeff)` to evaluate it without thinking about efficiency.

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop.

(This is already implemented in `np.poly1d`, but use that only to test your function)

- Hint: Use `np.cumprod()`  


In [22]:
import numpy as np

def p(x, coeff):
    '''
    - use np.ones_like to create array as long as the length of coeff
    - np.cumprod() to do x ** n
    - coeff * y would be elementwise product whereas coeff @ y does the matrix product
    '''
    y = np.ones_like(coeff) 
    y[1:] = x #since the first number is to the power 0
    z = np.cumprod(y) 
    return coeff @ y 

p(4, [5, 2, 3])

25

## Exercise 3 Softmax

Read in `data/iris.csv` and compute the [softmax]() of the sepal length. The formula for the softmax function $\sigma(x)$ for a vector $x = \{x_0, x_1, ..., x_{n-1}\}$ is
    .$$\sigma(x)_j = \frac{e^{x_j}}{\sum_k e^{x_k}}$$


Your result should be equal to the output of `scipy.special.softmax`

In [53]:
df = pd.read_csv('C:/Users/farha/Documents/m1-6-numpy/data/iris.csv')
array = df['sepallength'].to_numpy()

array2 = np.exp(array - np.max(array))
array2 / array2.sum()

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [55]:
from scipy.special import softmax

softmax(array)

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

## Exercise 4: unique counts


Compute the counts of unique values row-wise.

Input:
```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```
Desired Output:
```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```
Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

In [10]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

def unique_counts(arr):
    counts_array = [np.unique(row, return_counts=True) for row in arr]
    return counts_array

unique_counts(arr)

[(array([1, 3, 4, 5, 6, 8, 9]), array([1, 2, 1, 1, 1, 2, 2], dtype=int64)),
 (array([ 1,  2,  3,  5,  7,  9, 10]),
  array([2, 1, 3, 1, 1, 1, 1], dtype=int64)),
 (array([2, 4, 5, 6, 8]), array([3, 2, 3, 1, 1], dtype=int64)),
 (array([ 1,  3,  4,  6,  8,  9, 10]),
  array([1, 2, 1, 1, 2, 1, 2], dtype=int64)),
 (array([1, 2, 3, 6, 7, 8, 9]), array([2, 2, 2, 1, 1, 1, 1], dtype=int64)),
 (array([ 1,  2,  3,  4,  5,  6,  9, 10]),
  array([1, 1, 1, 1, 1, 2, 2, 1], dtype=int64))]

## Exercise 5: One-Hot encodings

Compute the one-hot encodings (AKA dummy binary variables) for each unique value in the array.

Input:
```
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])
```
Output:
```
#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])
```

In [2]:
import numpy as np

np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
print(arr)

def one_hot_encoder(arr):
    columns = np.max(arr) + 1
    one_hot_encoded = np.eye(columns)[arr]
    z = np.delete(one_hot_encoded, 0, 1) #delete extra column of zeros
    return z

one_hot_encoder(arr)

[2 3 2 2 2 1]


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

## Exercise 6

Let `q` be a NumPy array of length `n` with `q.sum() == 1`.

Suppose that `q` represents a [probability mass function](https://en.wikipedia.org/wiki/Probability_mass_function) over a statistical distribution. Recall that a distribution is an array of probabilities of events.

We want to generate a discrete random variable $ x $ such that $ \mathbb P\{x = i\} = q_i $.

In other words, `x` takes values in `range(len(q))` and `x = i` with probability `q[i]`.

The standard (inverse transform) algorithm is as follows:

- Divide the unit interval $ [0, 1] $ into $ n $ subintervals $ I_0, I_1, \ldots, I_{n-1} $ such that the length of $ I_i $ is $ q_i $.  
- Draw a uniform random variable $ U $ on $ [0, 1] $ and return the $ i $ such that $ U \in I_i $.  


The probability of drawing $ i $ is the length of $ I_i $, which is equal to $ q_i $.

We can implement the algorithm as follows

```python
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]
```

If you can’t see how this works, try thinking through the flow for a simple example, such as `q = [0.25, 0.75]`
It helps to sketch the intervals on paper.

**Your exercise is to speed it up using NumPy, avoiding explicit loops**

- Hint: Use `np.searchsorted` and `np.cumsum`  


If you can, implement the functionality as a class called `DiscreteRV`, where

- the data for an instance of the class is the vector of probabilities `q`  
- the class has a `draw()` method, which returns one draw according to the algorithm described above  


If you can, write the method so that `draw(k)` returns `k` draws from `q`.

In [9]:
from numpy.random import uniform
import numpy as np

def sample(q):
    x = np.cumsum(q)
    return x.searchsorted(uniform(0, 1))

sample(np.array([0.25, 0.75]))

1

In [5]:
def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]

sample([0.25, 0.75])

1

## Exercise 7 Peaks

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```
where, 2 and 5 are the positions of peak values 7 and 6.

### 1. Solve this usign a regular python for loop

### 2. Solve this using no loops and only numpy functions

In [97]:
#USING FOR LOOP

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

def peaks(a):
    peak_indices = []
    
    for i in range(1, len(a)-1):
        if a[i] > a[i - 1] and a[i] > a[i + 1]:
            peak_indices.append(i)
            
    return peak_indices

peaks(a)

[2, 5]

In [11]:
#USING NUMPY

import numpy as np

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

difference = np.diff(a)
x = np.diff(np.sign(difference)) #diff two times to find the local maximums
print(x)
peak_indices = np.where(x == -2)[0] + 1
peak_indices

[ 0 -2  2  0 -2  2]


array([2, 5], dtype=int64)

In [12]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

peaks = a[1:-1][np.diff(np.diff(a)) < 0]
peaks

array([7, 6])