## 1. What is the Average Height of US Presidents?

Aggregates available in NumPy can be extremely useful for summarizing a set of values.
As a simple example, let's consider the heights of all US presidents.

This data is available in the file *president_heights.csv*, which is a simple comma-separated list of labels and values.

Find the mean height, the standard deviation of height, and the president who is the smallest and tallest.

You can use `pandas` to read in the file if you want, then cast the column to a `np.array`

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv(r'C:\Users\David\Documents\code\m1-6-numpy\data\president_heights.csv')
pres_height = np.asarray( df['height(cm)'] )

np.mean(pres_height)

# Exercise 2

Recall the polynomial formula

$$
p(x) = a_0 + a_1 x + a_2 x^2 + \cdots a_N x^N = \sum_{n=0}^N a_n x^n \tag{1}
$$

In the **math functions workshop**, you wrote a simple function `p(x, coeff)` to evaluate it without thinking about efficiency.

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop.

(This is already implemented in `np.poly1d`, but use that only to test your function)

- Hint: Use `np.cumprod()`  


In [ ]:
def p(x, coeff):
    a = np.arange(len(coeff))
    b = x**a
    b[0] = coeff[0]
    print(b, ", Total:", sum(b))

p(5, [2, 1, 1])

## Exercise 3 Softmax

Read in `data/iris.csv` and compute the [softmax]() of the sepal length. The formula for the softmax function $\sigma(x)$ for a vector $x = \{x_0, x_1, ..., x_{n-1}\}$ is
    .$$\sigma(x)_j = \frac{e^{x_j}}{\sum_k e^{x_k}}$$


Your result should be equal to the output of `scipy.special.softmax`

In [ ]:
import scipy

df = pd.read_csv(r'C:\Users\David\Documents\code\m1-6-numpy\data\iris.csv')
sepal_array = np.asarray( df['sepallength'] )


sepal_softmax =  np.exp(sepal_array) / np.sum(np.exp(sepal_array))

print( sepal_softmax[:5] )

print( scipy.special.softmax(sepal_array)[:5] )


## Exercise 4: unique counts


Compute the counts of unique values row-wise.

Input:
```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```
Desired Output:
```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```
Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

In [197]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

arr_split = np.vsplit(arr, 6)

filler_ = np.zeros_like(arr)
filler = np.vsplit(filler_, 6)

for i in range(len(arr)):
        uniques, counts = np.unique(arr[i], return_counts=True)
        filler_[i, uniques-1] = counts

print(filler_)


[[1 0 2 1 1 1 0 2 2 0]
 [2 1 3 0 1 0 1 0 1 1]
 [0 3 0 2 3 1 0 1 0 0]
 [1 0 2 1 0 1 0 2 1 2]
 [2 2 2 0 0 1 1 1 1 0]
 [1 1 1 1 1 2 0 0 2 1]]


## Exercise 5: One-Hot encodings

Compute the one-hot encodings (AKA dummy binary variables) for each unique value in the array.

Input:
```
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])
```
Output:
```
#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])
```

In [ ]:
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr

shape = (arr.size, arr.max()+1)
hot_wings = np.zeros(shape)
rows = np.arange(arr.size)
hot_wings[rows, arr] = 1
print(hot_wings)

## Exercise 6

Let `q` be a NumPy array of length `n` with `q.sum() == 1`.

Suppose that `q` represents a [probability mass function](https://en.wikipedia.org/wiki/Probability_mass_function) over a statistical distribution. Recall that a distribution is an array of probabilities of events.

We want to generate a discrete random variable $ x $ such that $ \mathbb P\{x = i\} = q_i $.

In other words, `x` takes values in `range(len(q))` and `x = i` with probability `q[i]`.

The standard (inverse transform) algorithm is as follows:

- Divide the unit interval $ [0, 1] $ into $ n $ subintervals $ I_0, I_1, \ldots, I_{n-1} $ such that the length of $ I_i $ is $ q_i $.  
- Draw a uniform random variable $ U $ on $ [0, 1] $ and return the $ i $ such that $ U \in I_i $.  


The probability of drawing $ i $ is the length of $ I_i $, which is equal to $ q_i $.

We can implement the algorithm as follows

```python
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]
```

If you can’t see how this works, try thinking through the flow for a simple example, such as `q = [0.25, 0.75]`
It helps to sketch the intervals on paper.

**Your exercise is to speed it up using NumPy, avoiding explicit loops**

- Hint: Use `np.searchsorted` and `np.cumsum`  


If you can, implement the functionality as a class called `DiscreteRV`, where

- the data for an instance of the class is the vector of probabilities `q`  
- the class has a `draw()` method, which returns one draw according to the algorithm described above  


If you can, write the method so that `draw(k)` returns `k` draws from `q`.

In [362]:
from numpy.random import uniform

def sample(q):
        U = uniform(0,1)
        return np.searchsorted(q, U)
        

sample([0.50, 0.25, 0.25])

3

## Exercise 7 Peaks

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```
where, 2 and 5 are the positions of peak values 7 and 6.

### 1. Solve this usign a regular python for loop

### 2. Solve this using no loops and only numpy functions

In [2]:
import numpy as np

#1. Solve this usign a regular python for loop

def Peaks(a):
    index_gen = range(len(a))
    peaky_points = []
    for ind in index_gen:
        if ind == 0:
            if a[ind] >= a[ind+1]:
                peaky_points.append(ind)
            else:
                pass
        if ind != 0 and ind != len(a)-1:
            if a[ind] >= a[ind-1] and a[ind] >= a[ind+1]:
                peaky_points.append(ind)
            else:
                pass
        if ind == len(a):
            if a[ind] >= a[ind-1]:
                peaky_points.append(ind)
    print(peaky_points)

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

Peaks(a)

#2. Solve this using no loops and only numpy functions

one_side = np.where(a[1:] < a[:-1], 1, 0)
two_side = np.where(a[1:] < a[:1], 1, 0)

peaks_are_2s = np.add(one_side, two_side)

#I don't know why this won't work.
print(np.argwhere(peaks_are_2s == 2))

[2, 5]
[[5]]
