## 1. What is the Average Height of US Presidents?

Aggregates available in NumPy can be extremely useful for summarizing a set of values.
As a simple example, let's consider the heights of all US presidents.

This data is available in the file *president_heights.csv*, which is a simple comma-separated list of labels and values.

Find the mean height, the standard deviation of height, and the president who is the smallest and tallest.

You can use `pandas` to read in the file if you want, then cast the column to a `np.array`

In [34]:
#import csv
import numpy as np
import pandas as pd
#import statistics as st
path = 'data\president_heights.csv'
df = pd.read_csv(path,sep=',')

arr = np.array(df)
h_arr = arr[:,2]
CI =2
sorted_arr = arr[arr[:,CI].argsort()]
print(arr[arr[:,2].argmax(),1],"Is the tallest president.")
print(arr[arr[:,2].argmin(),1],"is the shortest president.")
print(f"the mean Height is :{int(h_arr.mean())}")
print(f"the stansdard deviation is: {round(np.std(h_arr))}")

Abraham Lincoln Is the tallest president.
James Madison is the shortest president.
the mean Height is :179
the stansdard deviation is: 7.0


In [3]:
print(f"the mean Height is :{int(h_arr.mean())}")
print(f"the shortest President is : {sorted_arr[0]}")
print(f"the talest President is : {sorted_arr[-1]}")




the mean Height is :179
the shortest President is : [4 'James Madison' 163]
the talest President is : [36 'Lyndon B. Johnson' 193]
the stansdard deviation is: 6.931843442745893


# Exercise 2

Recall the polynomial formula

$$
p(x) = a_0 + a_1 x + a_2 x^2 + \cdots a_N x^N = \sum_{n=0}^N a_n x^n \tag{1}
$$

In the **math functions workshop**, you wrote a simple function `p(x, coeff)` to evaluate it without thinking about efficiency.

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop.

(This is already implemented in `np.poly1d`, but use that only to test your function)

- Hint: Use `np.cumprod()`  


In [15]:
def p(x,coeff):
    xarr = np.array(x)
    carr = np.array(coeff)
    return np.cumsum(carr*(xarr**range(len(carr))))[-1]

In [16]:
p([5],[2,1,1])

32

## Exercise 3 Softmax

Read in `data/iris.csv` and compute the [softmax]() of the sepal length. The formula for the softmax function $\sigma(x)$ for a vector $x = \{x_0, x_1, ..., x_{n-1}\}$ is
    .$$\sigma(x)_j = \frac{e^{x_j}}{\sum_k e^{x_k}}$$


Your result should be equal to the output of `scipy.special.softmax`

In [37]:
import scipy as sc
import pandas as pd
df = pd.read_csv('data/iris.csv')



arr = np.array(df)
sepal = np.array(arr[:,0],dtype=float)
# Verification code ==>   print(sc.special.softmax(sepal))


print(np.exp(sepal) / np.sum(np.exp(sepal)))


[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

## Exercise 4: unique counts


Compute the counts of unique values row-wise.

Input:
```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```
Desired Output:
```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```
Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

In [1]:
import numpy as np
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr_result = np.zeros((6,10),dtype=int)
print(arr)


for i in range(0,6):
    for j in range(0,10):
        val2 = arr[i,:]
        arr_result[i,j] =  np.count_nonzero (np.where(val2==j+1,val2,j+1==val2))

print(arr_result)

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]
[[1 0 2 1 1 1 0 2 2 0]
 [2 1 3 0 1 0 1 0 1 1]
 [0 3 0 2 3 1 0 1 0 0]
 [1 0 2 1 0 1 0 2 1 2]
 [2 2 2 0 0 1 1 1 1 0]
 [1 1 1 1 1 2 0 0 2 1]]


## Exercise 5: One-Hot encodings

Compute the one-hot encodings (AKA dummy binary variables) for each unique value in the array.

Input:
```
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])
```
Output:
```
#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])
```

In [12]:
import numpy as np
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr2 = np.array([1,2,3])
arr_result = np.zeros((6,3),dtype=float)
print(arr)

for i in range(len(arr)):
    for j in range(0,3):
        val2 = arr[i]
        arr_result[i,:] = np.where(arr2==val2,1,val2 ==arr2)
        
print(arr_result)


[2 3 2 2 2 1]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


## Exercise 6

Let `q` be a NumPy array of length `n` with `q.sum() == 1`.

Suppose that `q` represents a [probability mass function](https://en.wikipedia.org/wiki/Probability_mass_function) over a statistical distribution. Recall that a distribution is an array of probabilities of events.

We want to generate a discrete random variable $ x $ such that $ \mathbb P\{x = i\} = q_i $.

In other words, `x` takes values in `range(len(q))` and `x = i` with probability `q[i]`.

The standard (inverse transform) algorithm is as follows:

- Divide the unit interval $ [0, 1] $ into $ n $ subintervals $ I_0, I_1, \ldots, I_{n-1} $ such that the length of $ I_i $ is $ q_i $.  
- Draw a uniform random variable $ U $ on $ [0, 1] $ and return the $ i $ such that $ U \in I_i $.  


The probability of drawing $ i $ is the length of $ I_i $, which is equal to $ q_i $.

We can implement the algorithm as follows

```python
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]
```

If you can’t see how this works, try thinking through the flow for a simple example, such as `q = [0.25, 0.75]`
It helps to sketch the intervals on paper.

**Your exercise is to speed it up using NumPy, avoiding explicit loops**

- Hint: Use `np.searchsorted` and `np.cumsum`  


If you can, implement the functionality as a class called `DiscreteRV`, where

- the data for an instance of the class is the vector of probabilities `q`  
- the class has a `draw()` method, which returns one draw according to the algorithm described above  


If you can, write the method so that `draw(k)` returns `k` draws from `q`.

In [24]:
np.searchsorted([1,2,3],2)

1

In [39]:
from random import uniform
import numpy as np
class DiscreteRV():
    def __init__(self,q):
        self.q = q
    
    def draw(self):
        u = uniform(0,1)
        #print(u)
        k = np.searchsorted( np.cumsum(self.q), u)
        
        return k


In [40]:
c= DiscreteRV([0.25, 0.25, 0.5])
c
c.draw()

2

In [54]:
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    print(U)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]

In [61]:
#sample ([0.25, 0.75])
sample ([0.25, 0.25, 0.5])

0.3134409964129311


1

## Exercise 7 Peaks

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```
where, 2 and 5 are the positions of peak values 7 and 6.

### 1. Solve this usign a regular python for loop

### 2. Solve this using no loops and only numpy functions

In [48]:
##    1     
import numpy as np
a = np.array([1, 3, 7, 1, 2, 6, 0 ,1])
b = np.array([],dtype=int)
for i in range(len(a)-1):
    if a[i+1] < a[i] > a[i-1] :
        b = np.append(b,i)

print(b)

[2 5]


In [49]:
##     2
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
#a = np.array([1, 3, 7, 1, 2, 6, 0, 1,4,1,5 ,4])
print( np.argwhere((np.logical_and(a[1:-1]>a[0:-2],a[1:-1]>a[2:] ))==True)+1)


[[2]
 [5]]


In [45]:
#import numpy as np
#print(np.diff([1,3,2]))



[ 2 -1]


In [74]:
##    2 detailed
#import numpy as np
aa = np.array([1, 3, 7, 1, 2, 6, 0, 1])
result = np.array((8),dtype=bool)
result = np.array([],dtype=bool)
a=aa[0:6]
b=aa[1:7]
c=aa[2:8] 
print(a,b,c)
result = np.logical_and(b>a,b>c)
fr= np.argwhere(result==True)
fr+1


[1 3 7 1 2 6] [3 7 1 2 6 0] [7 1 2 6 0 1]


array([[2],
       [5]], dtype=int64)