In [ ]:
# Bruno Ugolini

## 1. What is the Average Height of US Presidents?

Aggregates available in NumPy can be extremely useful for summarizing a set of values.
As a simple example, let's consider the heights of all US presidents.

This data is available in the file *president_heights.csv*, which is a simple comma-separated list of labels and values.

Find the mean height, the standard deviation of height, and the president who is the smallest and tallest.

You can use `pandas` to read in the file if you want, then cast the column to a `np.array`

In [20]:
import numpy as np
import pandas as pd

# Read in the dataset and look at the first rows.
data = pd.read_csv('./data/president_heights.csv')
data.head()

order               name  height(cm)
0      1  George Washington         189
1      2         John Adams         170
2      3   Thomas Jefferson         189
3      4      James Madison         163
4      5       James Monroe         183

In [21]:
heights = np.array(data['height(cm)'])
print(('The average height of a US president '
       'is {0:0.2f} cm with a standard deviation '
       'of {1:0.2f}.').format(np.average(heights), np.std(heights)))

The average height of a US president is 179.74 cm with a standard deviation of 6.93.


In [22]:
max_h = max(heights)
min_h = min(heights)
tallest = ', '.join(data.name.loc[data['height(cm)'] == max_h])
shortest = ', '.join(data.name.loc[data['height(cm)'] == min_h])
print(('The tallest presidents were {} '
       'with a height of {} cm.').format(tallest, max_h))
print(('The shortest presidents were {} '
       'with a height of {} cm.').format(shortest, min_h))

The tallest presidents were Abraham Lincoln, Lyndon B. Johnson with a height of 193 cm.
The shortest presidents were James Madison with a height of 163 cm.


# Exercise 2

Recall the polynomial formula

$$
p(x) = a_0 + a_1 x + a_2 x^2 + \cdots a_N x^N = \sum_{n=0}^N a_n x^n \tag{1}
$$

In the **math functions workshop**, you wrote a simple function `p(x, coeff)` to evaluate it without thinking about efficiency.

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop.

(This is already implemented in `np.poly1d`, but use that only to test your function)

- Hint: Use `np.cumprod()`  


In [25]:
import numpy as np

def p(a, x):
    """
    Evaluates a polynomial with coefficients a
    and for a value x using the Numpy package.
    """
    # create an array merging the
    # coefficients and the x^n terms
    b = np.array([a, 
                  np.array([x ** n for n in range(len(a))])])
    # reshape the array properly
    b.reshape(2, len(a))
    # take cummulative sum across columns
    c = np.cumprod(b, axis=0)
    # return the sum of the products
    return sum(c[1,:])

a = np.array([-2.1, 1.3, 0.43, -0.12, 0.14])
print(f"My result -> : \t\t{p(a, 0.5):0.5f}")
# validate result agains poly1d
pp = np.poly1d(a[::-1])
print(f"Numpy.poly1d -> : \t{pp(0.5):0.5f}")

My result -> : 		-1.34875
Numpy.poly1d -> : 	-1.34875


## Exercise 3 Softmax

Read in `data/iris.csv` and compute the [softmax]() of the sepal length. The formula for the softmax function $\sigma(x)$ for a vector $x = \{x_0, x_1, ..., x_{n-1}\}$ is
    .$$\sigma(x)_j = \frac{e^{x_j}}{\sum_k e^{x_k}}$$


Your result should be equal to the output of `scipy.special.softmax`

In [26]:
import numpy as np
import pandas as pd

# Read in the dataset and look at the first rows.
data = pd.read_csv('./data/iris.csv')
data.head()

sepallength  sepalwidth  petallength  petalwidth       flower
0          5.1         3.5          1.4         0.2  Iris-setosa
1          4.9         3.0          1.4         0.2  Iris-setosa
2          4.7         3.2          1.3         0.2  Iris-setosa
3          4.6         3.1          1.5         0.2  Iris-setosa
4          5.0         3.6          1.4         0.2  Iris-setosa

In [28]:
# retrieve the required column as an np.array
sepall = np.array(data['sepallength'])

# calculate the softmax value using numpy features
softmax = np.exp(sepall) / np.sum(np.exp(sepall))
softmax

array([0.00221959, 0.00181724, 0.00148783, 0.00134625, 0.00200836,
       0.00299613, 0.00134625, 0.00200836, 0.00110221, 0.00181724,
       0.00299613, 0.00164431, 0.00164431, 0.00099732, 0.0044697 ,
       0.00404435, 0.00299613, 0.00221959, 0.00404435, 0.00221959,
       0.00299613, 0.00221959, 0.00134625, 0.00221959, 0.00164431,
       0.00200836, 0.00200836, 0.00245302, 0.00245302, 0.00148783,
       0.00164431, 0.00299613, 0.00245302, 0.00331123, 0.00181724,
       0.00200836, 0.00331123, 0.00181724, 0.00110221, 0.00221959,
       0.00200836, 0.00121813, 0.00110221, 0.00200836, 0.00221959,
       0.00164431, 0.00221959, 0.00134625, 0.00271101, 0.00200836,
       0.01483991, 0.00814432, 0.01342771, 0.00331123, 0.00900086,
       0.00404435, 0.00736928, 0.00181724, 0.00994749, 0.00245302,
       0.00200836, 0.00493978, 0.0054593 , 0.00603346, 0.00365948,
       0.01099368, 0.00365948, 0.0044697 , 0.006668  , 0.00365948,
       0.00493978, 0.00603346, 0.00736928, 0.00603346, 0.00814

In [31]:
import scipy
#check result against SciPy Softmax
scipy.special.softmax(sepall) - softmax

array([1.73472348e-18, 1.73472348e-18, 1.30104261e-18, 1.30104261e-18,
       2.16840434e-18, 3.03576608e-18, 1.30104261e-18, 2.16840434e-18,
       1.08420217e-18, 1.73472348e-18, 3.03576608e-18, 1.51788304e-18,
       1.51788304e-18, 8.67361738e-19, 4.33680869e-18, 3.46944695e-18,
       3.03576608e-18, 1.73472348e-18, 3.46944695e-18, 1.73472348e-18,
       3.03576608e-18, 1.73472348e-18, 1.30104261e-18, 1.73472348e-18,
       1.51788304e-18, 2.16840434e-18, 2.16840434e-18, 2.16840434e-18,
       2.16840434e-18, 1.30104261e-18, 1.51788304e-18, 3.03576608e-18,
       2.16840434e-18, 3.03576608e-18, 1.73472348e-18, 2.16840434e-18,
       3.03576608e-18, 1.73472348e-18, 1.08420217e-18, 1.73472348e-18,
       2.16840434e-18, 1.08420217e-18, 1.08420217e-18, 2.16840434e-18,
       1.73472348e-18, 1.51788304e-18, 1.73472348e-18, 1.30104261e-18,
       2.16840434e-18, 2.16840434e-18, 1.56125113e-17, 8.67361738e-18,
       1.21430643e-17, 3.03576608e-18, 8.67361738e-18, 3.46944695e-18,
      

## Exercise 4: unique counts


Compute the counts of unique values row-wise.

Input:
```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```
Desired Output:
```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```
Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

In [33]:
import numpy as np

# repeat given code to get arr
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr

array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
       [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
       [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
       [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
       [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
       [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

In [34]:
# create array from 1 to 10
tst = np.arange(1,11)
# create an array of size equal to arr
res = np.zeros_like(arr)
for i in tst:
    # for each number, find matches 
    # everywhere in array and set = 1
    fnd =  np.where(arr == i, 1, 0)
    # equate the sums per row with the 
    # required answer per column
    res[:,i-1] = np.sum(fnd, axis=1)
# quick check: should have sum of 10 per row
print(np.sum(res, axis=1))
res

[10 10 10 10 10 10]


array([[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
       [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
       [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
       [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
       [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]])

## Exercise 5: One-Hot encodings

Compute the one-hot encodings (AKA dummy binary variables) for each unique value in the array.

Input:
```
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])
```
Output:
```
#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])
```

In [35]:
import numpy as np

# repeat the code given
np.random.seed(101)
arr = np.random.randint(1, 4, size=6)
print(f"Array = {arr}")

# initialize the results array with only zeros.
res = np.zeros((len(arr), 3))
# use fancy indexing to set correct values to
res[np.array(list(range(len(arr)))), arr-1] = 1
res

Array = [2 3 2 2 2 1]


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

## Exercise 6

Let `q` be a NumPy array of length `n` with `q.sum() == 1`.

Suppose that `q` represents a [probability mass function](https://en.wikipedia.org/wiki/Probability_mass_function) over a statistical distribution. Recall that a distribution is an array of probabilities of events.

We want to generate a discrete random variable $ x $ such that $ \mathbb P\{x = i\} = q_i $.

In other words, `x` takes values in `range(len(q))` and `x = i` with probability `q[i]`.

The standard (inverse transform) algorithm is as follows:

- Divide the unit interval $ [0, 1] $ into $ n $ subintervals $ I_0, I_1, \ldots, I_{n-1} $ such that the length of $ I_i $ is $ q_i $.  
- Draw a uniform random variable $ U $ on $ [0, 1] $ and return the $ i $ such that $ U \in I_i $.  


The probability of drawing $ i $ is the length of $ I_i $, which is equal to $ q_i $.

We can implement the algorithm as follows

```python
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]
```

If you can’t see how this works, try thinking through the flow for a simple example, such as `q = [0.25, 0.75]`
It helps to sketch the intervals on paper.

**Your exercise is to speed it up using NumPy, avoiding explicit loops**

- Hint: Use `np.searchsorted` and `np.cumsum`  


If you can, implement the functionality as a class called `DiscreteRV`, where

- the data for an instance of the class is the vector of probabilities `q`  
- the class has a `draw()` method, which returns one draw according to the algorithm described above  


If you can, write the method so that `draw(k)` returns `k` draws from `q`.

In [38]:
"""
re-cast the code without for loops
and using numpy functionality
"""
import numpy as np

q = np.array([0.10, 0.25, 0.25, 0.4])

# re-cast the above intervals into
# their absolute endpoints in [0,1]
qcsum = np.cumsum(q)

U = np.random.uniform(0, 1)

# get the interval (and corresponding element
# of q where the U lies
res = np.searchsorted(qcsum, U)

print(f"q => \t\t{q}")
print(f"qcsum => \t{qcsum}")
print(f"U => \t\t{U}")
print(f"result => \t\t{res}")

q => 		[0.1  0.25 0.25 0.4 ]
qcsum => 	[0.1  0.35 0.6  1.  ]
U => 		0.7215438617683047
result => 		3


In [39]:
import numpy as np

class DiscreteRV():

    def __init__(self, q=None):
        try:
            self.q = np.asarray(q, dtype='float32')
            self.csum = np.cumsum(self.q)
        except ValueError:
            return 'The array is ill-defined.'

    def __repr__(self):
        return 'q => ' + str(self.q)

    def draw(self, k=1):
        res = np.array(k)
        U = np.random.uniform(0, 1, size=k)
        #print(f"U: {U}")
        res = [np.searchsorted(self.csum, u) for u in U] 
        #print(f"    Result: {res}")
        return res

tst = DiscreteRV([0.1, 0.25, 0.25, 0.4])

tst.draw(5)


[1, 2, 2, 1, 3]

In [46]:
"""
Testing for a large number of cases 
to see the convergence of the results.

NOTE: I know this was not asked but 
      I was curious to view results.
"""
q = [0.1, 0.1, 0.20, 0.6]
qcsum = np.cumsum(q)
tst = DiscreteRV(q)
# Number of draws
N = [50, 200, 1000, 10000]
d1 = tst.draw(N[0])
d2 = tst.draw(N[1])
d3 = tst.draw(N[2])
d4 = tst.draw(N[3])

# plot results
import matplotlib.pyplot as plt


fig = plt.figure(figsize=(12, 7), dpi=500)
labels = ['N=' + str(i) for i in N]
plt.hist([d1, d2, d3, d4], density=True, 
         label=labels, bins=[0, 1, 2, 3, 4])
plt.grid(True)
plt.legend()
plt.ylabel('Counts normalized to probability density but with equal bin width')
plt.title('q = ' + str(q), x=0.5, y=0.9)
plt.savefig('Check__PMF.svg', bbox_inches='tight', dpi=500)
plt.close(fig)

<img src="Check__PMF.svg" />

## Exercise 7 Peaks

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```
where, 2 and 5 are the positions of peak values 7 and 6.

### 1. Solve this usign a regular python for loop

### 2. Solve this using no loops and only numpy functions

In [47]:
"""
Solution using regular Python
for loops (i.e. the way my brain
works)
"""
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

res = []
for i in range(1, len(a)-1):
    if a[i-1] < a[i] > a[i+1]:
        res.append(i)

res

[2, 5]

In [53]:
"""
Solution using Numpy functionality
"""
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

# shift to the left ...
b = np.roll(a, -1)
# shift to the right ...
c = np.roll(a, 1)
res = np.intersect1d(np.where(b < a), np.where(c < a))

print(f"b(left shift) : \t{b}")
print(f"a(original) : \t\t{a}")
print(f"b(right shift) : \t{c}")
print(f"solution: \t\t{res}")

b(left shift) : 	[3 7 1 2 6 0 1 1]
a(original) : 		[1 3 7 1 2 6 0 1]
b(right shift) : 	[1 1 3 7 1 2 6 0]
solution: 		[2 5]
