## 1. What is the Average Height of US Presidents?

Aggregates available in NumPy can be extremely useful for summarizing a set of values.
As a simple example, let's consider the heights of all US presidents.

This data is available in the file *president_heights.csv*, which is a simple comma-separated list of labels and values.

Find the mean height, the standard deviation of height, and the president who is the smallest and tallest.

You can use `pandas` to read in the file if you want, then cast the column to a `np.array`

In [4]:
import pandas
import numpy as np

df = pandas.read_csv('data/president_heights.csv')

height_list = df['height(cm)'].to_numpy()

mean_height = np.mean(height_list)
std_height = np.std(height_list)

print(mean_height)
print(std_height)


179.73809523809524
6.931843442745892


# Exercise 2

Recall the polynomial formula

$$
p(x) = a_0 + a_1 x + a_2 x^2 + \cdots a_N x^N = \sum_{n=0}^N a_n x^n \tag{1}
$$

In the **math functions workshop**, you wrote a simple function `p(x, coeff)` to evaluate it without thinking about efficiency.

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop.

(This is already implemented in `np.poly1d`, but use that only to test your function)

- Hint: Use `np.cumprod()`  

```
p(5, [1, 1]) = 1 + 5 = 6
p(5, [2, 1, 1]) = 2 + 5 + 25 = 31
```

In [40]:
import numpy as np

def p(x, coeff: np.array):
    """ returns the result of a polynomial
    :param x: value in given a point x
    :param coeff: Numpy array of numbers
    :returns: results of polynomial
    """
    # grab a 0
    total = coeff[0]**0
    # remove first item
    coeff_to_calc = np.delete(coeff, 0)
    # prepare arrays to calc powers
    constant_list = np.ones(coeff.size - 1)*5
    powers = np.delete(np.arange(0, coeff.size ), 0)
    # return final 
    return total + np.power(constant_list, powers).sum()
    

print(p(5, np.array([1, 1])))
print(p(5, np.array([2, 1, 1])))

6.0
31.0


## Exercise 3 Softmax

Read in `data/iris.csv` and compute the [softmax]() of the sepal length. The formula for the softmax function $\sigma(x)$ for a vector $x = \{x_0, x_1, ..., x_{n-1}\}$ is
    .$$\sigma(x)_j = \frac{e^{x_j}}{\sum_k e^{x_k}}$$


Your result should be equal to the output of `scipy.special.softmax`

In [47]:
import pandas as pd
import numpy as np

def get_softMax():
    df = pd.read_csv('data/iris.csv')

    logits = df['sepallength'].to_numpy()

    exponants = np.array([np.exp(logit) for logit in logits])
    exponants_sum = exponants.sum()

    return np.array([softmax/exponants_sum for softmax in exponants])

print(get_softMax())

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

## Exercise 4: unique counts


Compute the counts of unique values row-wise.

Input:
```
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])
```
Desired Output:
```
> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
```
Output contains 10 columns representing numbers from 1 to 10. The values are the counts of the numbers in the respective rows.
For example, Cell(0,2) has the value 2, which means, the number 3 occurs exactly 2 times in the 1st row.

In [103]:
from collections import Counter
import numpy as np

np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))

def find_uniques(int_list):
    counted = Counter(int_list)
    return np.array([counted[i] for i in int_list])

uniques = lambda int_lists: np.apply_along_axis(find_uniques, 0, int_lists)

print(arr)
print(uniques(arr))

[[ 9  9  4  8  8  1  5  3  6  3]
 [ 3  3  2  1  9  5  1 10  7  3]
 [ 5  2  6  4  5  5  4  8  2  2]
 [ 8  8  1  3 10 10  4  3  6  9]
 [ 2  1  8  7  3  1  9  3  6  2]
 [ 9  2  6  5  3  9  4  6  1 10]]
[[2 1 1 1 1 2 1 3 3 2]
 [1 1 1 1 1 2 1 1 1 2]
 [1 2 2 1 1 2 3 1 1 2]
 [1 1 1 1 1 1 3 3 3 1]
 [1 1 1 1 2 2 1 3 3 2]
 [2 2 2 1 2 1 3 1 1 1]]


## Exercise 5: One-Hot encodings

Compute the one-hot encodings (AKA dummy binary variables) for each unique value in the array.

Input:
```
np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])
```
Output:
```
#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])
```

In [158]:
from collections import Counter
import numpy as np

START = 1
STOP = 4
np.random.seed(101) 
arr = np.random.randint(START,STOP, size=6)

def get_one_hot_array(x):
    zeros = np.zeros(STOP-START)
    zeros[x-1] = 1
    return zeros

one_hot_matrix = lambda int_list: np.array([get_one_hot_array(i) for i in int_list])


print(one_hot_matrix(arr))

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


## Exercise 6

Let `q` be a NumPy array of length `n` with `q.sum() == 1`.

Suppose that `q` represents a [probability mass function](https://en.wikipedia.org/wiki/Probability_mass_function) over a statistical distribution. Recall that a distribution is an array of probabilities of events.

We want to generate a discrete random variable $ x $ such that $ \mathbb P\{x = i\} = q_i $.

In other words, `x` takes values in `range(len(q))` and `x = i` with probability `q[i]`.

The standard (inverse transform) algorithm is as follows:

- Divide the unit interval $ [0, 1] $ into $ n $ subintervals $ I_0, I_1, \ldots, I_{n-1} $ such that the length of $ I_i $ is $ q_i $.  
- Draw a uniform random variable $ U $ on $ [0, 1] $ and return the $ i $ such that $ U \in I_i $.  


The probability of drawing $ i $ is the length of $ I_i $, which is equal to $ q_i $.

We can implement the algorithm as follows

```python
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]
```

If you can’t see how this works, try thinking through the flow for a simple example, such as `q = [0.25, 0.75]`
It helps to sketch the intervals on paper.

**Your exercise is to speed it up using NumPy, avoiding explicit loops**

- Hint: Use `np.searchsorted` and `np.cumsum`  


If you can, implement the functionality as a class called `DiscreteRV`, where

- the data for an instance of the class is the vector of probabilities `q`  
- the class has a `draw()` method, which returns one draw according to the algorithm described above  


If you can, write the method so that `draw(k)` returns `k` draws from `q`.

In [243]:
from random import uniform
import numpy as np

# def sample(q):
#     a = 0.0
#     U = uniform(0, 1)
#     for i in range(len(q)):
#         print(a, U, q[i])
#         if a < U <= a + q[i]:
#             return i
#         a = a + q[i]
# sample([0.25,0.75])

class DiscreteRV:
    def __init__(self, q):
        self.q = np.array(q)
        if(self.q.cumsum()[-1] != 1):
            raise Exception('q.sum must be 1 otherwise not valid')

    def draw(self, k):
        return [np.searchsorted(self.q, uniform(0, 1)) for i in range(k)]

    
DiscreteRV([0.25,0.5, 0.25]).draw(5)
    

[1, 3, 3, 0, 1]

## Exercise 7 Peaks

Find all the peaks in a 1D numpy array a. Peaks are points surrounded by smaller values on both sides.

Input:
```
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
```
Desired Output:
```
#> array([2, 5])
```
where, 2 and 5 are the positions of peak values 7 and 6.

### 1. Solve this usign a regular python for loop

### 2. Solve this using no loops and only numpy functions

In [168]:
# 1
def peaks(array):
    not_edges = lambda x : x is not 0 and x is not len(array) -1
    is_peak = lambda a,b,c : array[a] > array[b] and array[a] > array[c]
    return [array[i] for i in range(len(array)) if not_edges(i) and is_peak(i, i -1, i + 1)]

peaks([1, 3, 7, 1, 2, 6, 0, 1])

[7, 6]

In [193]:
import numpy as np

def strided_app(a, L, S ): 
    nrows = ((a.size-L)//S)+1
    n = a.strides[0]
    return np.lib.stride_tricks.as_strided(a, shape=(nrows,L), strides=(S*n,n))

check_if_peak = lambda x: x[1] if x[1] > x[0] and x[1] > x[2] else 0

def numpy_peaks(array):
    result = np.apply_along_axis(check_if_peak, 1, strided_app(array, 3, 1))
    return result[result.nonzero()] 

numpy_peaks(np.array([1, 3, 7, 1, 2, 6, 0, 1]))

array([7, 6])